### ISSUE TITLE
Examples refactoring needed

### ISSUE THREAD

**Issue by wenjing** [twister2016/twister#47]
The examples code need some refactoring to address a few issues. For simplicity, I'm documenting these several problems in one Issue item.

The issues:
1. for each example, there is a port-config file, as is right now. this is not the desired behavior. The port config file is similar to /etc/ifconfig/xxx, ie. configuration of network interfaces (tw0, tw1, are similar to eth0, eth1,...). so this config should be twister wide. Since we may also have more config parameters, the name should just be config, not port config. If it's json, we should then name it "config.json".
2. The location/directory where this port config file resides should be /etc/twister/config.json.
3. The default content in the file must be correct without editing (it does not have to be useful, but must be correct.) E.g. a commented out example. 
4. The default config.json should be installed in the install step automatically.
5. README doc should talk about how to customize config.json.
6. Currently, all examples have their own directory and doc. This is highly wasteful since each example is so small. Also, we would like to use these examples as useful tools too. Let's change the directory to ./applications. Move all example code under one directory and one makefile. Each example can have one .c file and optionally one .h file. Make in ./applications should install all example executables.
7. application executables should be automatically installed to /usr/bin/twister. 
8. README doc should explain to add /usr/bin/twister to PATH as necessary.
9. All single example documentation should be merged to one single doc for now.
10. all example code should use consistent naming: all lower case, all one word without dash or underscore, with preceding tw. names should copy linux equivalent. e.g. twarp, ...

**Comment by chaudhryusama** [comment]
This issue has been addressed in the following commit
https://github.com/twister2016/twister/commit/10eb4d4009a29ffb7649265533eb8505d1fada8e

**Comment by wenjing** [comment]
I think some items are not resolved yet: (2), (3), (5), (6), (7), (9).

**Comment by wriaz** [comment]
Only (9) is not resolved, all others are fixed in latest commits.
